# After staring container, don't forget to install db :
#   docker exec -it airnotifier python /airnotifier/install.py

version: "3"
services:
  airnotifier:
    network_mode: host
    build: .
    container_name: airnotifier
    volumes:
      - ${AIRNOTIFIER_CERTS:-../var/airnotifier/certs}:/var/airnotifier/pemdir
      - ${AIRNOTIFIER_LOGS:-../var/airnotifier/logs}:/var/log/airnotifier
#    ports:
#      - 8801:8801
    environment:
      - MONGO_SERVER=${MONGO_SERVER:-mongodb}
      - MONGO_PORT=${MONGO_PORT:-27017}
