# After staring container, don't forget to install db :
#   docker exec -it airnotifier python /airnotifier/install.py

version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/tmp/mongo/mongo.log
    volumes:
      - ${MONGO_DATA:-../var/mongo/data}:/data/db
      - ${MONGO_LOG:-../var/mongo/log}:/tmp/mongo
    command: mongod --logpath=/dev/null # --quiet
  airnotifier:
    links:
      - mongodb
    depends_on:
      - mongodb
    build: .
    container_name: airnotifier
    volumes:
      - ${AIRNOTIFIER_CERTS:-../var/airnotifier/certs}:/var/airnotifier/pemdir
      - ${AIRNOTIFIER_LOGS:-../var/airnotifier/logs}:/var/log/airnotifier
    ports:
      - 8801:8801
    environment:
      - MONGO_SERVER=${MONGO_SERVER:-mongodb}
      - MONGO_PORT=${MONGO_PORT:-27017}
